version: 2

linters:
  enable-all: true
  disable:
    - execinquery

linters-settings:
  gocognit:
    min-complexity: 50

issues:
  exclude-rules:
    # Ignore os.Remove errors - cleanup code
    - linters: [errcheck]
      text: "os.Remove"
    # Ignore os.Setenv/Unsetenv
    - linters: [errcheck]
      text: "os.Setenv"
    - linters: [errcheck]
      text: "os.Unsetenv"
    # Ignore fmt.Fprintf errors - output rarely matters
    - linters: [errcheck]
      text: "fmt.Fprintf"
    - linters: [errcheck]
      text: "fmt.Fprintln"
