version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - goconst
    - gocognit
    - misspell
    - revive
  settings:
    gocognit:
      min-complexity: 50
    revive:
      rules:
        - name: var-naming
          disabled: true
