version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - goconst
    - misspell
  settings:
    gosec:
      excludes:
        # G101: Hardcoded credentials - false positives in test files with example data
        - G101
        # G115: Integer overflow uintptr->int - standard Go pattern for terminal/fd detection
        - G115
        # G204: Subprocess with variable - we validate image names before exec
        - G204
    staticcheck:
      checks:
        - "all"
        - "-QF1012" # WriteString(fmt.Sprintf) style suggestion - not a bug
