version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - goconst
    - misspell
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF1012" # WriteString(fmt.Sprintf) style suggestion - not a bug
