# GitHub Actions - PR Scanning with Changed Files
#
# This workflow scans only the files changed in a pull request for faster feedback.
# Uses tj-actions/changed-files to detect modified files.
#
# Benefits:
#   - Faster scan times (only changed files)
#   - Focused results on PR changes
#   - Excludes test files that may contain intentional security patterns
#
# Required secrets:
#   - ARMIS_API_TOKEN: Your Armis API token
#   - ARMIS_TENANT_ID: Your Armis tenant identifier

name: PR Security Scan

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write

jobs:
  get-changed-files:
    name: Get Changed Files
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changed-files.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          separator: ','
          # Exclude test files from security scan
          # They may contain intentional security patterns for testing
          files_ignore: |
            **/*_test.go
            **/*_test.js
            **/*_test.ts
            **/*.test.js
            **/*.test.ts
            **/*.spec.js
            **/*.spec.ts
            **/testdata/**
            **/fixtures/**
            **/__tests__/**

  security-scan:
    name: Security Scan
    needs: get-changed-files
    if: needs.get-changed-files.outputs.any_changed == 'true'
    uses: ArmisSecurity/armis-cli/.github/workflows/reusable-security-scan.yml@main
    with:
      scan-type: repo
      fail-on: 'CRITICAL,HIGH'
      include-files: ${{ needs.get-changed-files.outputs.files }}
    secrets:
      api-token: ${{ secrets.ARMIS_API_TOKEN }}
      tenant-id: ${{ secrets.ARMIS_TENANT_ID }}
