stages:
  - security

security-scan:
  stage: security
  image: alpine:latest
  
  before_script:
    - apk add --no-cache curl bash docker
  
  script:
    - curl -sSL https://raw.githubusercontent.com/ArmisSecurity/armis-cli/main/scripts/install.sh | bash
    - armis-cli scan repo . --format json --fail-on HIGH,CRITICAL
  
  variables:
    ARMIS_API_TOKEN: $ARMIS_API_TOKEN
  
  only:
    - main
    - merge_requests
